// src/lib.rs
pub mod pb {
    pub mod vectordb {
        pub mod v1 {
            // Generated by tonic-build into src/pbgen/…
            include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/pbgen/vectordb.v1.rs"));
        }
    }
}

pub mod catalog;
pub mod index;
pub mod storage;
pub mod types;
pub mod telemetry;

pub mod server {
    pub mod state;
    pub mod grpc;
}
